// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: esp32p4

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_uiButtonStart = NULL;
lv_obj_t * ui_uiLabelDataName = NULL;
lv_obj_t * ui_uiLabelDataValue = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiButtonStart = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_uiButtonStart, 150);
    lv_obj_set_height(ui_uiButtonStart, 100);
    lv_obj_set_x(ui_uiButtonStart, -276);
    lv_obj_set_y(ui_uiButtonStart, 29);
    lv_obj_set_align(ui_uiButtonStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiButtonStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uiButtonStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiLabelDataName = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLabelDataName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelDataName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelDataName, -17);
    lv_obj_set_y(ui_uiLabelDataName, 28);
    lv_obj_set_align(ui_uiLabelDataName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelDataName, "CARBORN DIOXIDE(CO2): waiting");

    ui_uiLabelDataValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLabelDataValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelDataValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelDataValue, 210);
    lv_obj_set_y(ui_uiLabelDataValue, 30);
    lv_obj_set_align(ui_uiLabelDataValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelDataValue, "Value: ---");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_uiButtonStart = NULL;
    ui_uiLabelDataName = NULL;
    ui_uiLabelDataValue = NULL;

}
